version: "3.9"

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: metabase-db
    depends_on:
      - metabase-db

  metabase-db:
    image: postgres:15
    container_name: metabase-db
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
    volumes:
      - metabase_data:/var/lib/postgresql/data

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    environment:
      DOZZLE_USERNAME=admin
      DOZZLE_EMAIL=admin@example.com
      DOZZLE_NAME=Admin
      DOZZLE_PASSWORD_HASH="$2a$11$wiV3BaRtU/25CWhBd68BM.f1bnFl8DNWDd0deslJbHHeg6ESWQD62"
